### ISSUE TITLE
no content in re-rendered component

### ISSUE THREAD

**Issue by fariedt** [yogthos/reagent-secretary-example#1]
I cloned the repo, ran `lein figwheel`, and loaded up the page in Chrome.  I made a change to the `home-page` component (added `[:p "hi"]` in the `[:div]`), waited for figwheel to re-render, and got a blank page.  The developer console has no warnings or errors, and the same problem occurs with Firefox.

I've tried creating a simple one-component project using `reagent-frontend`, and verified that figwheel does re-render properly when I make changes to my component.  This is with both reagent `0.7.0` and `0.8.0-rc1`.  I've also tried setting `:load-warninged-code true` in figwheel's config, under `:cljsbuild`.

I'm not sure how to debug this further.

**Comment by yogthos** [comment]
Oh sorry, turns out it was a typo on my part. The `selected-page` atom was being initialized to `:home` and should've been initialized to `home-page` instead. When the core namespace was being reloaded, it would get set correctly on the initial load by the route, but then when the namespace was reloaded by figwheel it would end up with `:home` as its value instead of the page.

**Comment by fariedt** [comment]
Thanks.  I should've noticed that, too!  I was trying to set up my own project using this one as a blueprint, and the error I got with reagent 0.8.0 threw me off at first (something like `<home> is not a valid component name`).  0.7.0 gave me a blank page.
